#!/usr/bin/env bash
# Production build of the AZ Mail frontend (one build for every environment).
#
# Usage: scripts/build_frontend.sh [--api-base URL] [--skip-checks]
#   --api-base URL  also write dist/config.js with this API origin (e.g. https://mail-api.example.com),
#                   for serving dist/ as is; a deployed web root keeps its own /config.js (DESIGN E2)
#   --skip-checks   skip `pnpm test` and `pnpm lint`
# Output: frontend/dist/ → scripts/deploy_frontend.sh copies it to the web root
#         (deploy/nginx-frontend.conf) and never overwrites the environment's config.js.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}/frontend"

API_BASE=""
CHECKS=1
while [ $# -gt 0 ]; do
  case "$1" in
    --api-base) API_BASE="$2"; shift ;;
    --skip-checks) CHECKS=0 ;;
    -h|--help) sed -n '2,9p' "${ROOT}/scripts/build_frontend.sh" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

command -v pnpm >/dev/null || { echo "pnpm is required (Node ≥ 22)" >&2; exit 1; }
echo "==> pnpm install --frozen-lockfile"
pnpm install --frozen-lockfile
if [ "${CHECKS}" = 1 ]; then
  echo "==> pnpm test && pnpm lint"
  pnpm test
  pnpm lint
fi
echo "==> pnpm build"
pnpm build

if [ -n "${API_BASE}" ]; then
  case "${API_BASE}" in
    http://*|https://*) ;;
    *) echo "--api-base must be an http(s) origin" >&2; exit 2 ;;
  esac
  API_BASE="${API_BASE%/}"
  cat > dist/config.js <<EOF
// AZ Mail runtime configuration (generated by scripts/build_frontend.sh).
window.__AZMAIL_CONFIG__ = { apiBase: "${API_BASE}" };
EOF
  echo "==> wrote dist/config.js (apiBase ${API_BASE})"
fi
echo "==> done: ${ROOT}/frontend/dist"
