# azmail_set_warnings(<target>): project-wide warning flags for our own targets.
function(azmail_set_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(AZMAIL_WERROR)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wno-unused-parameter)
    if(AZMAIL_WERROR)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
